version: "2"

services:
  puppet_server:
    image: devopsil/puppetmaster
    tty: true
    stdin_open: true
    volumes:
      - ./puppet_server/etc/puppet:/etc/puppet
  puppet_production_balancer:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes:
      - ./production/balancer/etc/puppet:/etc/puppet
      - ./production/balancer/opt/haproxy:/opt/haproxy
    depends_on: ['puppet_server']
    ports: ['5000:5000', '5001:5001']
  production_blue1:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes: ['./production/blue1/etc/puppet:/etc/puppet']
    depends_on: ['puppet_server']
  production_blue2:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes: ['./production/blue2/etc/puppet:/etc/puppet']
    depends_on: ['puppet_server']
  production_blue3:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes: ['./production/blue3/etc/puppet:/etc/puppet']
    depends_on: ['puppet_server']
  production_green1:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes: ['./production/green1/etc/puppet:/etc/puppet']
    depends_on: ['puppet_server']
  production_green2:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes: ['./production/green2/etc/puppet:/etc/puppet']
    depends_on: ['puppet_server']
