version: "2"

services:
  puppet_server:
    image: devopsil/puppetmaster
    tty: true
    stdin_open: true
    volumes:
      - ./puppet_server/etc/puppet:/etc/puppet
  puppet_production_balancer:
    image: devopsil/puppet
    command: tail -f /dev/null
    links: ['puppet_server:puppet']
    volumes:
      - ./production/balancer/etc/puppet:/etc/puppet
      - ./production/balancer/opt/haproxy:/opt/haproxy
    depends_on: ['puppet_server']
    ports: ['5000:5000', '5001:5001']
