deploy_strategy:
  groups:
    blue:
      app_version: v0.0.2
      frontend_port: 5001
      clients:
        - production_blue1
        - production_blue2
        - production_blue3
    green:
      app_version: v0.0.3
      frontend_port: 5002
      clients:
        - production_green1
        - production_green2
